version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  commands:
    - pip install uv
    - cd py-oxbow && uv sync --group=docs && uv run --group=docs sphinx-build ../docs $READTHEDOCS_OUTPUT/html

sphinx:
  configuration: docs/conf.py