version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  apt_packages:
    - graphviz
  jobs:
    pre_install:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
    build:
      html:
        - cd py-oxbow && uv sync --group=docs && uv run --group=docs sphinx-build ../docs $READTHEDOCS_OUTPUT/html

sphinx:
  configuration: docs/conf.py