[build-system]
requires = ["maturin>=1.3.0,<1.4"]
build-backend = "maturin"

[project]
name = "oxbow"
dynamic = ["version"]
description = "Read specialized bioinformatic file formats into dataframes."
authors = [
    { name = "Oxbow Developers", email = "nabdennur@gmail.com" }
]
license = { text = "MIT OR Apache-2.0" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]

[project.urls]
homepage = "https://github.com/abdenlab/oxbow"

[tool.maturin]
features = ["pyo3/extension-module"]

[tool.hatch.envs.default]
dependencies = [
    "jupyterlab",
    "pandas",
    "polars",
    "pyarrow",
    "pysam",
]

[tool.hatch.envs.docs]
dependencies = [
    "furo",
    "myst_parser>=0.13",
    "sphinx>=4.0",
    "sphinx-autobuild",
    "sphinx-book-theme>=0.1.0",
    "sphinx_copybutton",
]
[tool.hatch.envs.docs.scripts]
build = "sphinx-build docs docs/_build/html"
serve = "sphinx-autobuild docs docs/_build/html"

[tool.hatch.envs.test]
dependencies = [
    "polars",
    "pytest",
]
[tool.hatch.envs.test.scripts]
all = "pytest {args:tests}"

[tool.ruff.isort]
known-first-party = ["oxbow"]
