name: Test

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

env:
  # Disable incremental compilation for faster from-scratch builds
  CARGO_INCREMENTAL: 0

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: rustup update

      # Typechecking
      - name: Run Cargo Check
        run: cargo check --all-targets --all-features

      # Linting
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      # Assert Formatting
      - name: Check Formatting
        run: cargo fmt --all --check

      # Tests
      - name: Download fixtures
        run: cd fixtures && wget -i list.txt

      - name: Run Tests
        run: cargo test
