name: Test

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

env:
  # Disable incremental compilation for faster from-scratch builds
  CARGO_INCREMENTAL: 0

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: rustup update

      - name: Check formatting
        run: cargo fmt --all --check

      - name: Download fixtures
        run: cd fixtures && wget -i list.txt

      - name: Run cargo test
        run: cargo test
