name: Test

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

env:
  # Disable incremental compilation for faster from-scratch builds
  CARGO_INCREMENTAL: 0

jobs:
  TestOxbow:
    name: "Test Rust"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: rustup update

      # Typechecking
      - name: Run Cargo Check
        run: cargo check -p oxbow -p py-oxbow --all-features

      # Linting
      - name: Install Clippy
        run: rustup component add clippy
      - name: Run Clippy
        run: cargo clippy -p oxbow -p py-oxbow --all-features -- -D warnings

        # Assert Formatting
      - name: Install rustfmt
        run: rustup component add rustfmt
      - name: Check Formatting
        run: cargo fmt --all --check

      # Tests
      - name: Download fixtures
        run: cd fixtures && wget -i list.txt

      - name: Run Tests
        run: cargo test -p oxbow -p py-oxbow --all-features

  TestPython:
    name: "Test Python"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: 
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'

    steps:
      - uses: actions/checkout@v4
      - run: rustup update
      - uses: astral-sh/setup-uv@v6
        with:
          pyproject-file: "py-oxbow/pyproject.toml"
          python-version: ${{ matrix.python-version }}
      - run: |
          cd py-oxbow/tests
          uv run --no-default-groups --dev pytest

  LintPython:
    name: "Lint Python"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: 
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          pyproject-file: "py-oxbow/pyproject.toml"
          python-version: ${{ matrix.python-version }}
      - run: |
          cd py-oxbow
          uv run --no-default-groups --only-group=dev ruff format --check
          uv run --no-default-groups --only-group=dev ruff check

